services:
  backend:
    volumes:
      - /root/karaoke_data/sqlite:/data/sqlite
      - /root/karaoke_data/media:/data/media

  worker:
    volumes:
      - /root/karaoke_data/sqlite:/data/sqlite
      - /root/karaoke_data/media:/data/media
      - /root/karaoke_data/models:/data/models

  qdrant:
    volumes:
      - /root/karaoke_data/qdrant:/qdrant/storage
